on: [issue_comment]

jobs:
  bossbot_issue_comment_cleanup:
    runs-on: ubuntu-latest
    name: BossBot - Github Issue Comment Cleanup
    steps:
      - uses: actions/checkout@v2
      - name: BossBot - Github Issue Comment Cleanup - action step
        uses: banagale/bossbot-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_ANNOTATION: true
